-- CreateEnum
CREATE TYPE "CallDirection" AS ENUM ('OUTBOUND', 'INBOUND');

-- AlterEnum CallStatus: add new values (PostgreSQL)
ALTER TYPE "CallStatus" ADD VALUE IF NOT EXISTS 'INITIATING';
ALTER TYPE "CallStatus" ADD VALUE IF NOT EXISTS 'IN_PROGRESS';
ALTER TYPE "CallStatus" ADD VALUE IF NOT EXISTS 'NO_ANSWER';
ALTER TYPE "CallStatus" ADD VALUE IF NOT EXISTS 'BUSY';
ALTER TYPE "CallStatus" ADD VALUE IF NOT EXISTS 'CANCELED';

-- AlterTable Call
ALTER TABLE "Call" ADD COLUMN IF NOT EXISTS "provider" TEXT NOT NULL DEFAULT 'twilio';
ALTER TABLE "Call" ADD COLUMN IF NOT EXISTS "providerCallId" TEXT;
ALTER TABLE "Call" ADD COLUMN IF NOT EXISTS "direction" "CallDirection" NOT NULL DEFAULT 'OUTBOUND';
ALTER TABLE "Call" ADD COLUMN IF NOT EXISTS "phoneNumber" TEXT;
ALTER TABLE "Call" ADD COLUMN IF NOT EXISTS "recordingUrl" TEXT;
ALTER TABLE "Call" ADD COLUMN IF NOT EXISTS "answeredAt" TIMESTAMP(3);
ALTER TABLE "Call" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

CREATE INDEX IF NOT EXISTS "Call_providerCallId_idx" ON "Call"("providerCallId");
CREATE INDEX IF NOT EXISTS "Call_status_idx" ON "Call"("status");
CREATE INDEX IF NOT EXISTS "Call_createdAt_idx" ON "Call"("createdAt");

-- AlterTable CallSummary
ALTER TABLE "CallSummary" ADD COLUMN IF NOT EXISTS "outcome" TEXT;
ALTER TABLE "CallSummary" ADD COLUMN IF NOT EXISTS "interestLevel" TEXT;
ALTER TABLE "CallSummary" ADD COLUMN IF NOT EXISTS "keyRequirements" TEXT[] DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "CallSummary" ADD COLUMN IF NOT EXISTS "painPoints" TEXT[] DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "CallSummary" ADD COLUMN IF NOT EXISTS "objectionList" TEXT[] DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "CallSummary" ADD COLUMN IF NOT EXISTS "followUpRecommended" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "CallSummary" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
