-- AlterTable
ALTER TABLE "LeadAnalysis" ADD COLUMN "buyingStage" TEXT,
ADD COLUMN "objections" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN "painPoints" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN "requirements" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN "source" TEXT NOT NULL DEFAULT 'seed',
ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
